### ISSUE TITLE
Select Details Layout

### ISSUE THREAD

**Issue by Anuragtech02** [1ezio/ietians-diary#17]
## Select Details
Check the design in the [Figma Design File](https://www.figma.com/file/ZH1dsdzj2Fcwt3zrX6BQ5b/Ietian-s-Diary?node-id=1%3A2) under the high fidelity section.

**Comment by gautamjain09** [comment]
I will do the task

**Comment by Anuragtech02** [comment]
Let us know if you face any issues @gautamjain09
