### ISSUE TITLE
Auth UI

### ISSUE THREAD

**Issue by Anuragtech02** [1ezio/ietians-diary#4]
### Create initial boilerplate + some basic design for authentication page(activity).

**Comment by gautamjain09** [comment]
I will like to take this issue

**Comment by adarsh434** [comment]
I would like to take this issue.

**Comment by adarsh434** [comment]
I would like to take this issue.

**Comment by adarsh434** [comment]
I would also like to take this issue.

**Comment by Anuragtech02** [comment]
@adarsh434 Please mention this issue next time in the PR
