### ISSUE TITLE
Replace LinearyLayout manager with GridLayoutManager in RoadmapAdapter

### ISSUE THREAD

**Issue by Anuragtech02** [1ezio/ietians-diary#48]
### Replace LinearyLayout manager with GridLayoutManager in the recycler view used in the file `RoadmapAdapter` 
- Remove staggered grid layout
- Look for a workaround for providing margin/padding to card based on the position
- Equal width of the roadmap cards in the grid (2 cols)

### Possible Solution
- Check if the `position` inside the Recycler view adapter is odd/even, based on that add padding to the right or left
 Something like this

  ```
    if(position % 2 == 0)
    {
    container.setPaddingRight(16);
    }
  ```

**Comment by adarsh434** [comment]
I have solved this issue, kindly assign me this and I will make a PR.
