### ISSUE TITLE
Mistakes in Readme

### ISSUE THREAD

**Issue by arinjaysaraf** [1ezio/ietians-diary#58]
- Typos'
- Android Logo not visible in dark mode
- Inappropriate sub-heading sizes

**Comment by Anuragtech02** [comment]
Hey, thanks for looking into it! I'll assign this to issue if you want to work on it.

**Comment by arinjaysaraf** [comment]
Yes I would like to work on it

**Comment by arinjaysaraf** [comment]
Thanks
